name: FactionMasterBank
author: ShockedPlot7560
version: 2.0.0
api: 4.0.0
main: ShockedPlot7560\FactionMasterBank\FactionMasterBank
src-namespace-prefix: ShockedPlot7560\FactionMasterBank
depend: [EconomyAPI, FactionMaster]
softdepend: ["ScoreHud"]
description: "Extension which implements a bank system"
